# Generated by Django 3.2.6 on 2021-09-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_age', models.IntegerField()),
                ('disease', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=10)),
                ('ward_no', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
            ],
        ),
    ]
